services:
  api:
    build: .
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: test_db
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ${ADBREW_CODEBASE_PATH:-./src}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH:-./src}:/src

  app:
    image: node:16
    container_name: app
    working_dir: /src/app
    command: bash -c "yarn install --frozen-lockfile && yarn start"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    stdin_open: true
    depends_on:
      - api
    volumes:
      - ${ADBREW_CODEBASE_PATH:-./src}:/src
      - app_node_modules:/src/app/node_modules

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ${ADBREW_CODEBASE_PATH:-./src}/db/:/data/db

volumes:
  app_node_modules:
